server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: springboottest.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: springboottest.utils.MyMapper
  not-empty: false
  identity: MYSQL