spring:
  datasource:
    # 这里使用mysql:3306是因为我的mysql是部署到docker中的，我们的容器需link mysql容器
    # 即使mysql部署在容器中，这里mysql也可以以IP:Port的形式配置，不过我们的容器需要设置参数--net=host
    url: jdbc:mysql://mysql:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  thymeleaf:
    cache: true